# Generated by Django 3.1.7 on 2021-05-04 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('apartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=100)),
                ('apartment_type', models.TextField(max_length=50)),
                ('description', models.TextField()),
                ('utilities', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='apartment_images')),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_header', models.TextField(max_length=150)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField()),
                ('is_sell_post', models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=5)),
                ('apartment_id', models.ForeignKey(db_column='apartment_id', on_delete=django.db.models.deletion.CASCADE, to='post.apartmentmodel')),
                ('email', models.ForeignKey(auto_created=True, db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
